version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - mongoose
    networks:
      - backend
    volumes:
      - .:/home/yugioh-crud-server/
  mongoose:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=oscar
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  backend: