version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - mongoose
    networks:
      - backend
    volumes:
      - .:/home/yugioh-crud-server/
  mongoose:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=oscar
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongoex:
    image: mongo-express
    ports:
        - "8081:8081"
    networks:
      - backend
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=oscar
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongoose

volumes:
  mongo-data:

networks:
  backend: